import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/header/Navbar";
import Sidebar from "../components/main/Sidebar";
import TakeInput from "../components/main/TakeInput";
import { AuthProvider } from "../context/Authcontext"; // ✅ Import AuthProvider
import { ToastContainer } from "react-toastify";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Wrap your app with AuthProvider */}
        <AuthProvider> 
          <Navbar />
          <div className="flex min-h-screen mt-5">
            <Sidebar />
            <div className="flex-1">
              <div className="min-h-[200px] flex justify-center items-center">
                <TakeInput />
              </div>
              {children}
              <ToastContainer />
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
